global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'server_name']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://backend:8000/api/v1/monitoring/alerts/webhook'
        send_resolved: true