"""add monitoring_enabled column to servers table

Revision ID: 0001
Revises: 
Create Date: 2025-10-23 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite兼容的方式添加布尔列并设置默认值
    op.add_column('servers', sa.Column('monitoring_enabled', sa.Boolean(), nullable=True))
    # 设置默认值
    op.execute("UPDATE servers SET monitoring_enabled = false WHERE monitoring_enabled IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'monitoring_enabled')
    # ### end Alembic commands ###