"""add monitoring_enabled column to servers table

Revision ID: 0001
Revises: 
Create Date: 2025-10-23 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # 尝试添加列，如果已经存在则会抛出异常
        op.add_column('servers', sa.Column('monitoring_enabled', sa.Boolean(), nullable=True))
        # 设置默认值
        op.execute("UPDATE servers SET monitoring_enabled = false WHERE monitoring_enabled IS NULL")
    except Exception as e:
        # 如果列已经存在，打印信息并继续
        if "duplicate column name" in str(e) or "duplicate" in str(e).lower():
            print("Column 'monitoring_enabled' already exists, skipping addition.")
        else:
            # 如果是其他错误，重新抛出
            raise e
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'monitoring_enabled')
    # ### end Alembic commands ###