"""add redfish_supported and redfish_version columns to servers table

Revision ID: 0002
Revises: 0001
Create Date: 2025-11-07 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        # 尝试添加Redfish支持相关列，如果已经存在则会抛出异常
        op.add_column('servers', sa.Column('redfish_supported', sa.Boolean(), nullable=True))
        op.add_column('servers', sa.Column('redfish_version', sa.String(20), nullable=True))
        # 设置默认值
        op.execute("UPDATE servers SET redfish_supported = NULL WHERE redfish_supported IS NULL")
    except Exception as e:
        # 如果列已经存在，打印信息并继续
        if "duplicate column name" in str(e):
            print("Redfish columns already exist, skipping addition.")
        else:
            # 如果是其他错误，重新抛出
            raise e
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('servers', 'redfish_version')
        op.drop_column('servers', 'redfish_supported')
    except Exception as e:
        # 如果列不存在，打印信息并继续
        if "no such column" in str(e).lower():
            print("Redfish columns do not exist, skipping removal.")
        else:
            # 如果是其他错误，重新抛出
            raise e
    # ### end Alembic commands ###