"""add redfish support fields

Revision ID: 002_add_redfish_support
Revises: 001_initial_migration
Create Date: 2023-11-07 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_redfish_support'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redfish_supported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('redfish_version', sa.String(length=20), nullable=True))
    
    # 设置默认值为NULL而不是False，因为我们想要区分"未检查"和"不支持"
    op.execute("UPDATE servers SET redfish_supported = NULL WHERE redfish_supported IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('redfish_version')
        batch_op.drop_column('redfish_supported')
    # ### end Alembic commands ###