# 全局配置
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'openshub-cluster'
    environment: 'production'

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # OpenServerHub API监控
  - job_name: 'openshub-api'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # IPMI服务器监控
  - job_name: 'ipmi-servers'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/ipmi-targets.json'
    scrape_interval: 60s
    scrape_timeout: 30s
    metrics_path: /metrics