# 全局配置
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'openshub-cluster'
    environment: 'development'

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # OpenServerHub API监控
  - job_name: 'openshub-api'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics
    scrape_interval: 15s

  # IPMI服务器监控
  - job_name: 'ipmi-servers'
    scrape_interval: 1m
    metrics_path: /metrics
    file_sd_configs:
    - files:
      - /etc/prometheus/targets/ipmi-targets.json
    relabel_configs:
    - source_labels: [module]
      target_label: __param_module
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: ipmi-exporter:9290